services:
  guzzle:
    class: \GuzzleHttp\Client

  exchange_rates.services_providers.tcmbprovider:
    class: ExchangeRatesBundle\Services\Providers\TCMBProvider
    arguments: ['@guzzle']

  exchange_rates.services_providers.fccprovider:
    class: ExchangeRatesBundle\Services\Providers\FCCProvider
    arguments: ['@guzzle']